### ISSUE TITLE
Allow use as main formatter

### ISSUE THREAD

**Issue by rock3r** [lipiridi/spotless-applier#19]
Hi! I was wondering if it could be possible to integrate the Spotless formatting with the "standard" formatting system in the IDE, so we don't have to remember using a dedicated shortcut.

It should be relatively easy. Looking at the ktfmt plugin, the steps seem to be:
1. Registering a `formattingService` extension in `plugin.xml`:
   
   ```xml
   <extensions defaultExtensionNs="com.intellij">
      <formattingService implementation="..."/>
      <!-- ... -->
   </extensions>
   ``` 
2. Implement `com.intellij.formatting.service.AsyncDocumentFormattingService`
3. Adding a setting to enable replacing the default formatter with Spotless

I don't think I'll have time to implement this by myself any time soon, but maybe someone else can. At least I thought I should test the waters and see if y'all like the idea :)

**Comment by lipiridi** [comment]
Hi @rock3r!
**ktfmt** is a code formatter, where **spotless** is a tool gives you the ability to use different formatters with own configuration.
That's why, there is no way to call spotless apply function somehow apart gradle task.

Plugin already supports "On Save" action allows you to apply spotless automatically (https://github.com/lipiridi/spotless-applier/issues/16) - https://github.com/lipiridi/spotless-applier?tab=readme-ov-file#action-on-save
In addition, you can just override the shortcut to any other you want:
![image](https://github.com/user-attachments/assets/df7e995d-3699-4aa3-ae87-53aeb490ab99)

**Comment by rock3r** [comment]
Thanks @lipiridi for the answer! I understand the technical constraints. As for the shortcut, that isn't something I had considered; however that is a global setting and not all projects I work on use spotless or ktfmt, unfortunately, so I can't replace the built-in formatter. I suppose I need to use the alternative shortcut in those projects, then.

**Comment by lipiridi** [comment]
Also wanted to say for the history - built-in formatters should support ability to format few files, when spotless gradle task supports either entire project or single file. But calling gradle task for each file in the package (for example) is much expensive and doesn't make sense.
Hope someday someone will write a useful connector to avoid gradle at all🙂
